create table clientes (id_cliente int4 generated by default as identity, cpf varchar(15) not null, email varchar(60), nome varchar(60) not null, observacao varchar(255), telefone varchar(15) not null, id_endereco int4 not null, primary key (id_cliente));
create table enderecos (id_endereco int4 generated by default as identity, bairro varchar(60) not null, cep varchar(15), complemento varchar(60), estado varchar(255), logradouro varchar(60) not null, municipio varchar(60), numero varchar(10) not null, primary key (id_endereco));
create table usuarios (id_usuario int4 generated by default as identity, email varchar(60) not null, nome varchar(60) not null, senha varchar(50) not null, primary key (id_usuario));
alter table if exists clientes add constraint UK_7wflw78ibh162cmq12ii6ffly unique (cpf);
alter table if exists clientes add constraint UK_1c96wv36rk2hwui7qhjks3mvg unique (email);
alter table if exists clientes add constraint UK_n04o2sb6gpxbq0j9r2dcurbbb unique (telefone);
alter table if exists usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table if exists clientes add constraint FKmcsl2xyk2sepb45sgmwgvh68q foreign key (id_endereco) references enderecos;
insert into usuarios (nome, email, senha) values ('Israel Fraga', 'is@bol.com', '81dc9bdb52d04dc20036dbd8313ed055');
