create table cliente (idcliente int4 generated by default as identity, cpf varchar(15) not null, email varchar(100) not null, nome varchar(150) not null, primary key (idcliente));
alter table if exists cliente add constraint UK_r1u8010d60num5vc8fp0q1j2a unique (cpf);
