create table cliente (idcliente int4 generated by default as identity, cpf varchar(15) not null, email varchar(100) not null, nome varchar(150) not null, primary key (idcliente));
alter table if exists cliente add constraint UK_r1u8010d60num5vc8fp0q1j2a unique (cpf);
insert into cliente (nome, cpf, email) values ('Israel Fraga', 11111111111, 'is@bol.com'), ('Edy Silva', 22222222222, 'edy@bol.com'), ('Ana Santos', 33333333333, 'ana@bol.com'),('Caio Braga', 44444444444, 'caio@bol.com');
